### ISSUE TITLE
`set newtabfocus page` doesn't work anymore

### ISSUE THREAD

**Issue by glacambre** [tridactyl/tridactyl#1122]
Linux+Tridactyl 1.14.1-8-g454a63e+Firefox 63

**Comment by dsdshcym** [comment]
Same issue here:
- Firefox 64.0b4
- macOS 10.14
- tridactyl 1.14.1-8-g454a63e

**Comment by antonva** [comment]
This looks like it's caused by the introduction of out of process extensions in Linux in version 63. This has been a feature of FF on Windows for a while which explains why `window.focus()` never worked on Windows.

[https://bugzilla.mozilla.org/show_bug.cgi?id=1415860](https://bugzilla.mozilla.org/show_bug.cgi?id=1415860)
[https://www.omgubuntu.co.uk/2018/08/out-of-process-extensions-firefox-linux](https://www.omgubuntu.co.uk/2018/08/out-of-process-extensions-firefox-linux)

**Comment by iago-lito** [comment]
Pressing `<tab><tab>` is enough to get the focus back. But should you forget, then you are tricked into url autocompletion so you need `<esc><tab><tab>` to fall back on your feet..  
Any other workaround so far?

**Comment by karioki** [comment]
> Pressing `<tab><tab>` is enough to get the focus back. But should you forget, then you are tricked into url autocompletion so you need `<esc><tab><tab>` to fall back on your feet..
> Any other workaround so far?

You can use F6.

**Comment by bovine3dom** [comment]
Fixed and setting removed in #2632

**Comment by Shane-XB-Qian** [comment]
why removed this `newtabfocus` setting (to `page`) ?
so now we had to use `F6` to workaround if we'd like to keep newtab focus on `page` (vs `urlbar`) by default ?!

**Comment by bovine3dom** [comment]
Mozilla broke it and we had no way of fixing it. `:tabopen` now puts focus on the page rather than the address bar anyway. Are you using ctrl-t to open new tabs? Don't do that and your problems should go away :)

**Comment by Shane-XB-Qian** [comment]
yes, `ctrl-t`, because it is more short and direct than `:tabopen`.
so deal was done, `newtabfocus` to `page` was gone for good for ever ?

anyway, `newtabfoucs` in/if `:set` or `:h` etc still showed there, but just now did not work anymore (even set to `page`). fyi.

**Comment by bovine3dom** [comment]
Mozilla might fix the bug someday but it isn't a high priority. That usually means it won't be fixed.

`newtabfocus` was removed a short while ago - you're probably using an old version of Tridactyl. The current :version is 1.20.1. We removed it precisely because it was broken and confusing people : )

I have a feeling you're using Tridactyl in a strange way. Usually one presses "t", types some fragment of a URL, presses tab to select a URL and then presses enter. I think you may be opening a new tab and then pressing "o" before following the same procedure. I can't imagine why else you would want focus to be on the page.

**Comment by Shane-XB-Qian** [comment]
good, thanks your info, probably i used to use `ctrl-t` since it was a common hotkey,
but your hint is very good, i can switch to use `t`, thanks!

i am using v80.0 ff in ubuntu, and tridactyl version 1.20.1 (last updated august 28, 2020)
when i inputed `:set newtabfoucs` i still can see the value was `page`, **it means it did not remove there.**
and `:h newtabfocus` can see the output as well, though can not search out `newtabfocus` in help/doc now.
anyway, this just is a fyi.

**Comment by bovine3dom** [comment]
That's probably because you set it yourself; we only removed the default setting. If you do `:unset newtabfocus` it should disappear. I think :)

**Comment by Shane-XB-Qian** [comment]
yes, as / same like this ticket's title, i set it `page` as demanded.

just feeling a little strange: if this setting (`newtabfocus`) was going to be removed, then this setting should be becoming a invalid option, means: this option and value should be removed as well, otherwise user perhaps no way to be notified: no clue to know thing/logic changed ..
but  this just a discussion and fyi, perhaps there was some ff tech limitation ..

anyway, your offered workaround and `F6` is ok if `newtabfocus` removed. thx.

**Comment by bovine3dom** [comment]
It was mentioned in the change log on the new tab page : )

I'm not sure what the alternative would be. I think having a pop-up explaining the bug + removal would be more annoying.

**Comment by Shane-XB-Qian** [comment]
i see, 
but unfortunately change log only existed on src repo here -vs- can not be found at `release note` of this extension in firefox ..

i means the alternative was: once one setting removed, then that setting removed totally (from `:set`) too - whatever user set it or not, then that would be a clue to user be notified sth had been changed .. and/but better explained it at help/doc -vs- just removed it.

**Comment by Shane-XB-Qian** [comment]
ok, whatever, i think this discussion should be good enough, 
just to general user that perhaps was a headache still, but to senior user probably was good enough already ..
so let it be, or put it into backlog, thanks your explain.

**Comment by bovine3dom** [comment]
> i see, but unfortunately change log only existed on src repo here

It's displayed on the new tab page, it's the big green button. Do you have the new tab page disabled? I don't know how to tell those users about the changes - any thoughts you have on that would be appreciated. I suppose we could have a button like Firefox does with its little present icon when there is a new changelog to read, but people who have the GUI disabled wouldn't see it.

I gave up on the Firefox release notes as I personally couldn't work out where they were displayed so I assumed no-one read them.

**Comment by Shane-XB-Qian** [comment]
> I suppose we could have a button like Firefox does with its little present icon when there is a new changelog to read

i think this should be a good idea, i saw some other extension of ff had such icon at the right side of urlbar, that probably a good way to notify user about the change-log after new release.

another option was like i said above: adding some explain about that sunset setting in e.g `:h newtabfocus` and/or help/doc, just like similar flow in normal vim (bram's vim).
