### ISSUE TITLE
Vimperator "hintfiltermode" for uppercase letters.

### ISSUE THREAD

**Issue by WloHu** [tridactyl/tridactyl#1775]
# Feature request.
*   Brief description of the problem:

I can't figure out if and how to:
- use letters for hinting,
- with filtering (a.k.a. "vimperator" mode),
- make hints react on uppercase letters only (I don't case about hint display case),
- so that I can use alphanumeric chars for filtering and uppercase alpha for hint triggering.

Reason: I come from VimFx where it was possible and I really liked that hint selection flow.

*   Steps to reproduce:
N/A

*   Tridactyl version (`:version`):
1.16.2pre2999-95db0a8

*   Firefox version (Top right menu > Help > About Firefox):
68.0.1 (64-bit)

*   URL of the website the bug happens on:
N/A

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):
Doesn't matter.

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

```
set hintfiltermode vimperator-reflow
set hintnames short
set hintuppercase true
set hintchars FDSERWGCVXZT
```

*   Operating system: Doesn't matter.
*   Result of running `:! echo $PATH`, or `! echo %PATH%` on Windows, in Tridactyl:
--
*   Unix-like only: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` in a terminal:
--

**Comment by bovine3dom** [comment]
Hmm, I'm sure this worked at some point. Someone with a French keyboard needed to press shift to access number keys IIRC. It's possible we broke it when we fixed that.

**Comment by WloHu** [comment]
Well in my case I can't get the letters as hints. I only get numbers.

**Comment by bovine3dom** [comment]
Are you sure you don't have `set hintnames numeric`?

On 1 August 2019 06:09:29 BST, WloHu <notifications@github.com> wrote:

Well in my case I can't get the letters as hints. I only get numbers.

**Comment by WloHu** [comment]
It turned out that I had `set hintnames numeric` in config at the bottom of file in section I've copied. Sorry for the confusion.

However I still can't use `vimperator-reflow` filtering with uppercase hint characters. Filtering works but hints aren't triggered when I use uppercase letters e.g. `<S-f>`.
