### ISSUE TITLE
tridactyl compatible wit FF ESR? (60.9)

### ISSUE THREAD

**Issue by MilanV** [tridactyl/tridactyl#1934]
Hello. I run firefox-esr now (Linux Debian 10 - there is no other FF package) and tridactyl beta looked breaking many sites - so I tried to reinstall it - to find the correct tridactyl version compatible with FF ESR. But I couldn't find any, although I tried older versions in Arch Linux repo recommended in tridactyl README.

Please, what's the correct XPI of tridactyl compatible with FF ESR?

**Comment by bovine3dom** [comment]
Version 1.14.13 - https://tridactyl.cmcaine.co.uk/tridactyl.vim.1.14.13.xpi

We should probably link to this on the readme.

**Comment by MilanV** [comment]
Thank you, this is the version I found mentioned on redit but with no link.
I may confirm it installs but, unfortunately, has the same bug as beta has: it makes some pages completely blank. Pages generated heavily by JS. Among them, my internet banking :(

This is what I found as a publicly visible example:
https://www.zbozi.cz/dum-byt-a-zahrada/nabytek/loznice/komody/?hloubka-nabytku-do=60&hloubka-nabytku-od=50

It's in Czech but checking the difference is easy even without the language knowledge: it should list some selected goods in e-shop search. With tridactyl, it shows (me) a blank page.

**Comment by MilanV** [comment]
Shall I open another issue then?

**Comment by bovine3dom** [comment]
> Shall I open another issue then?

Please do. FWIW, that page opens fine for me with Tridactyl running.

![](https://i.imgur.com/xuFFwDb.png)

**Comment by glacambre** [comment]
Maybe this is something we fixed in cd868ca04c5e9dd4f628d8c33bafaab34bbe6f3d ?

**Comment by bovine3dom** [comment]
1.14.13 contains that code :)

**Comment by MilanV** [comment]
OK, it doesn't make any sense to start a new thread, so far. Unfortunately I'm not able to reproduce the problem with fresh-new profile. Although the "old" profile has the problem even when I disable all extensions but tridactyl (and disappears when tridactyl gets disabled), new profiles with the same tridactyl version works.
The only two possible differences I know about is that the old profile
1. was converted from the profile of previous FF ESR version (i.e. before 60.0)
2. that profile contains manual modification for black tridactyl theme (and I forgot what exactly it is)

Do you think it may be the problem source, one or the other?

**Comment by bovine3dom** [comment]
Are there any Tridactyl settings in the old profile you care about? It could be being caused by one of them (I think `set allowautofocus false` has broken some sites before, for example).

If you wipe them with `sanitise tridactyllocal tridcatylsync` and restart, does the problem persist?

**Comment by MilanV** [comment]
It was not needed. It works now after these steps:
1. remove userChrome.css (containing a code for placing locationbar down and removing top tabbar)
2. remove all extensions (needed step)
3. reinstall tridactyl from the link above (version 14.3)
4. restart FF
5. install TreeTab extension and restart FF again

Before that, if I left TreeTab extension in my profile and just reinstalled tridactyl, the page at zbozi.cz worked but my internet banking (Raiffeisenbank) did not. After the steps above (remove everything, install tridactyl as the first one, restart FF (needed) and then install treetab again) it started to work.

**Comment by bovine3dom** [comment]
That's very odd. I'll leave this open but I don't think we'll have any luck chasing that bug down as it looks complicated to trigger.
