### ISSUE TITLE
Tab history (back/forward) list

### ISSUE THREAD

**Issue by johnbeard** [tridactyl/tridactyl#242]
The Firefox [history](https://developer.mozilla.org/en-US/docs/Web/API/History) API doesn't allow a WebExt (or webpage) to see the tab history list. You can only go back by a count (e.g. `history.back() === history.go(-1) === Tridactyl "H" nmap`). Lame.

However, Tridactyl is more betterer than dumb page JS, and it could maintain its own per-tab forward/back history list which can be used in a completion-list for `back` and `forward`.

It would probably take a little bit of finagling to ensure it keeps in sync with the FF version accessed by right-clicking on the back/forward arrows, but I _think_ it would be possible.

**Comment by oxysoft** [comment]
+1 to this, I often used to right-click the back button to access the previous pages jump-list. A command to access that same jump-list (or a mirror, since it seems like Firefox does not make this available to webextensions...) through the command line would be awesome.

**Comment by ivcz** [comment]
I want to work on this, but i imagine it thee same as tab command autocomplete with history of the current tab which is made from jumplist with page titles added to it. Is it an okay way to approach it?

**Comment by bovine3dom** [comment]
I think so, yeah.

I'd really like eventually to have tab history as a tree (so when you click back you get a new leaf - I'm not 100% sure how it would best work) so it would be nice if whatever you made made adding that somewhat easy.

**Comment by ivcz** [comment]
I thought about it and i feel like it would be better to store separate from jumps as a linked list. Either way will i need to make a new completion provider or do i somehow feed the list to the history one?

**Comment by bovine3dom** [comment]
I think it would be easiest to make a new completion provider : )

If we merged them we'd have to worry about duplicates which seems like it could be slow + a pain

**Comment by ivcz** [comment]
Finally got enough time to get back on this
So I decided against using separate list since its basically just back() and next() calls with completion and just add title and favicon to jumplist instead
But I have a problem with curJumps(), jumplist seems to only be updating on jumpprev() or jumpnext() calls, I tried calling addJump() on page load but it doesnt help, what am I missing?

**Comment by bovine3dom** [comment]
Have you tried adding `addJump()` here: https://github.com/tridactyl/tridactyl/blob/da9bea7edf63dd3ec24bd44c120cb72d6530ee18/src/excmds.ts#L1089 ?

If you're doing it elsewhere it might be called before Tridactyl is fully working.

By the way, I should warn you that I'm currently rewriting completions from scratch. I can't guarantee that it will ever get finished but I have started it: #3896 . If it does get finished the completions side of this will need to be rewritten.

**Comment by ivcz** [comment]
Yeah, I also tried adding it on DOMContentLoaded but it still doesnt show up until I explicitly call curJumps() or addJump() from somewhere else

Ok, I will look into completions when I get this to work properly

**Comment by glacambre** [comment]
>But I have a problem with curJumps(), jumplist seems to only be updating on jumpprev() or jumpnext() calls

This doesn't match what I'm seeing. Using `:js tri.excmds.curJumps().then(j => alert(JSON.stringify(j)))` prints multiple jumps, even right after loading the first page of a new tab.

**Comment by ivcz** [comment]
Actually addJump() on DOMContentLoaded seems to work fine, but if I dont add it 
`        const tabs = await browserBg.tabs.query({ active: true, currentWindow: true })
          let jumps = await browserBg.sessions.getTabValue(tabs[0].id, "jumps")
`
in the completions returns nothing until I call curJumps() or anything related to addJump()

**Comment by hemanti0503** [comment]
@ivcz, thank you for all your work on this! I'm looking forward to the feature. :) Are you still working on it?

**Comment by ivcz** [comment]
> @ivcz, thank you for all your work on this! I'm looking forward to the feature. :) Are you still working on it?

I've been pretty busy lately and forgot about this feature, I think I'll be able to take a look at it in a couple of days
