### ISSUE TITLE
Issue in border-bottom declaration

### ISSUE THREAD

**Issue by wschmrdr** [tridactyl/tridactyl#698]
When opening any page (including the new tab page), the following is found in the console:

Error in parsing value for ‘border-bottom’.  Declaration dropped.
commandline.css:96:29

There's also a few debug statements in there. Not sure if those are intentional at the current version, but I would assume the error is not.
Tridactyl 1.7.3, Firefox 60.0.2 64-bit, Linux Mint 18.

**Comment by bovine3dom** [comment]
> Tridactyl 1.7.3

@wschmrdr that's an ancient version of Tridactyl. Current version is 1.13.0. Please check the Firefox UI for any tiny yellow exclamation marks that are asking you for more permissions before Tridactyl is allowed to update. About 1/5 of our users are stuck on this version for this reason.

**Comment by wschmrdr** [comment]
OK. Sort of wish that was a little more obvious, but never the less, I'm now up to 1.13.0. At this time, although commandline.css is fixed, I'm now seeing several other errors; here's what I'm seeing:

Error in parsing value for ‘padding’.  Declaration dropped.
newtab.css:26:20
Unknown property ‘user-select’.  Declaration dropped.
content.css:38:17
Expected declaration but found ‘!’.  Skipped to next declaration.
hint.css:26:54
Expected declaration but found ‘!’.  Skipped to next declaration.
hint.css:42:32
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: onclick attribute on LABEL element.
newtab.html
No export func
content.ts:65:4
Error in parsing value for ‘outline’.  Declaration dropped.
cleanslate.css:65:13
Unknown property ‘-moz-background-size’.  Declaration dropped.
cleanslate.css:93:29
Unknown property ‘-moz-border-radius’.  Declaration dropped.
cleanslate.css:100:27
Unknown property ‘-moz-column-span’.  Declaration dropped.
cleanslate.css:117:25
Unknown property ‘column-span’.  Declaration dropped.
cleanslate.css:118:25
Unknown property ‘s
’.  Declaration dropped.
cleanslate.css:266:1
Error in parsing value for ‘background’.  Declaration dropped.
cleanslate.css:289:17
Error in parsing value for ‘background’.  Declaration dropped.
cleanslate.css:290:17
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.
cleanslate.css:292:13
Unknown property ‘-moz-box-shadow’.  Declaration dropped.
cleanslate.css:294:24
Error in parsing value for ‘outline’.  Declaration dropped.
cleanslate.css:328:22
Error in parsing value for ‘outline’.  Declaration dropped.
cleanslate.css:342:14
Error in parsing value for ‘background’.  Declaration dropped.
cleanslate.css:352:17
Error in parsing value for ‘background’.  Declaration dropped.
cleanslate.css:353:17

The cleanslate.css ones are carrying over to other sites.

**Comment by bovine3dom** [comment]
> wish that was a little more obvious

Me too! We're explicitly told we're not allowed to update outside of the Mozilla channels, but we can probably add a notification to the new tab page...

Could you give an example of a site where you see these errors?

**Comment by glacambre** [comment]
@bovine3dom To see these errors you need to enable them. Go to the console, click on the funnel icon and click on the `CSS` button. The fix is simple, just fork cleanslate and use our own version. I talked a bit about it here: https://github.com/cmcaine/tridactyl/issues/339#issuecomment-395751405 .

**Comment by glacambre** [comment]
@wschmrdr I don't see errors caused by Tridactyl anymore, can you still reproduce this bug?

**Comment by glacambre** [comment]
Mozilla did a pretty good job at separating extension errors from page errors in the last few releases and I'm not seeing CSS errors from Tridactyl anymore. I'm closing this issue, please let us know if you can still reproduce it.
